### ISSUE TITLE
Setup Styled Components Theming

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#2]
# Description
Setup Styled Components Theming 

# Resources

* https://styled-components.com/docs/advanced#theming

# Acceptance Criteria

* Theme capablities setup (although not the actual theme)

**Comment by lokesh75way** [comment]
- Created new branch `issue/#2--setup-styled-components-theming` from `issue/#1--setup-styled-components` branch (because it’s dependent on issue/#1).
- Completed  `issue/#2--setup-styled-components-theming`
- PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/16
- Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/4ac3cbcbf8dbda92923128f9d2957fe1f2a6a466

**Comment by lokesh75way** [comment]
- Merged branch `issue/#1--setup-styled-components` to branch `issue/#2--setup-styled-components-theming`
- Done: Feedback fixes
- Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/228eb5f92ec73187831f440938d6eaf8528b5e4d
- PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/16

**Comment by lokesh75way** [comment]
- Moved ThemeProvider to `app.js` file.
- Separated ThemeProvider from `Theme.jsx`.
- Deleted `styled.declare.ts` file and created interface (DefaultTheme) into `Theme.jsx`.
- PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/16
- Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/7dcc009891a1ecc75a9a38f7134a364048f276ca
